Try to fix dns/dnstracer port (issue with gmake)
poudriere log:

====>> Status for build dns/dnstracer: build
(00:00:04) =======================<phase: build          >============================
(00:00:04) ===>  Building for dnstracer-1.9
(00:00:04) gmake[1]: Entering directory '/wrkdirs/usr/ports/dns/dnstracer/work/dnstracer-1.9'
(00:00:04) cd . && /bin/sh ./config.status Makefile depfiles
(00:00:04) config.status: error: invalid argument: depfiles
(00:00:04) Makefile:132: recipe for target 'Makefile' failed
(00:00:04) gmake[1]: *** [Makefile] Error 1
(00:00:04) gmake[1]: Leaving directory '/wrkdirs/usr/ports/dns/dnstracer/work/dnstracer-1.9'
(00:00:04) ===> Compilation failed unexpectedly.
(00:00:04) Try to set MAKE_JOBS_UNSAFE=yes and rebuild before reporting the failure to
(00:00:04) the maintainer.
(00:00:04) *** Error code 1
(00:00:04)
(00:00:04) Stop.
(00:00:04) make: stopped in /usr/ports/dns/dnstracer

It's hard to reproduce (job unsafe maybe). I removed USES=gmake, because:
- it fixes the problem
- gmake is not required to build this port